name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          reviewers: matthewcottell
          assignees: matthewcottell
